import { Inter } from 'next/font/google';
import StyledJsxRegistry from './lib/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Ztaar +',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
